# Generated by Django 4.2.10 on 2025-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="libro",
            name="imagen",
        ),
        migrations.AlterField(
            model_name="libro",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="libro",
            name="autores_ids",
            field=models.ManyToManyField(related_name="libros", to="libreria.autor"),
        ),
    ]
