# Generated by Django 4.2.10 on 2025-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0002_autor_remove_libro_imagen_alter_libro_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="autores_ids",
            field=models.ManyToManyField(
                related_name="libros", to="libreria.autor", verbose_name="Autores"
            ),
        ),
    ]
