# Generated by Django 4.2.10 on 2025-01-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0003_alter_libro_autores_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="fecha_nacimiento",
        ),
        migrations.AddField(
            model_name="autor",
            name="pais",
            field=models.CharField(default="", max_length=100),
        ),
    ]
